/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectPlanRouteImport } from './routes/select-plan'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PosRouteRouteImport } from './routes/_pos/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AdminAppRouteRouteImport } from './routes/_adminApp/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AdminAuthRouteImport } from './routes/admin.auth'
import { Route as PosTimeclockRouteImport } from './routes/_pos/timeclock'
import { Route as PosRegisterRouteImport } from './routes/_pos/register'
import { Route as PosRefundsRouteImport } from './routes/_pos/refunds'
import { Route as PosPosRouteImport } from './routes/_pos/pos'
import { Route as DashboardShiftsRouteImport } from './routes/_dashboard/shifts'
import { Route as DashboardSetupRouteImport } from './routes/_dashboard/setup'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardSalesRouteImport } from './routes/_dashboard/sales'
import { Route as DashboardReportsRouteImport } from './routes/_dashboard/reports'
import { Route as DashboardProductsRouteImport } from './routes/_dashboard/products'
import { Route as DashboardPayrollRouteImport } from './routes/_dashboard/payroll'
import { Route as DashboardOnboardingRouteImport } from './routes/_dashboard/onboarding'
import { Route as DashboardInventoryRouteImport } from './routes/_dashboard/inventory'
import { Route as DashboardHelpRouteImport } from './routes/_dashboard/help'
import { Route as DashboardEmployeesRouteImport } from './routes/_dashboard/employees'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCustomersRouteImport } from './routes/_dashboard/customers'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AdminAppAdminIndexRouteImport } from './routes/_adminApp/admin.index'
import { Route as LovableSmsSendRouteImport } from './routes/lovable/sms/send'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as DashboardEmployeesIdRouteImport } from './routes/_dashboard/employees.$id'
import { Route as AdminAppAdminSupportRouteImport } from './routes/_adminApp/admin.support'
import { Route as AdminAppAdminSubscriptionsRouteImport } from './routes/_adminApp/admin.subscriptions'
import { Route as AdminAppAdminSettingsRouteImport } from './routes/_adminApp/admin.settings'
import { Route as AdminAppAdminDevicesRouteImport } from './routes/_adminApp/admin.devices'
import { Route as AdminAppAdminAuditLogsRouteImport } from './routes/_adminApp/admin.audit-logs'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AdminAppAdminBusinessesIndexRouteImport } from './routes/_adminApp/admin.businesses.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPosVerifyManagerPinRouteImport } from './routes/api/public/pos/verify-manager-pin'
import { Route as ApiPublicPosVerifyEmployeePinRouteImport } from './routes/api/public/pos/verify-employee-pin'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AdminAppAdminSupportTicketIdRouteImport } from './routes/_adminApp/admin.support.$ticketId'
import { Route as AdminAppAdminBusinessesStoreIdRouteImport } from './routes/_adminApp/admin.businesses.$storeId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectPlanRoute = SelectPlanRouteImport.update({
  id: '/select-plan',
  path: '/select-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRouteRoute = PosRouteRouteImport.update({
  id: '/_pos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppRouteRoute = AdminAppRouteRouteImport.update({
  id: '/_adminApp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PosTimeclockRoute = PosTimeclockRouteImport.update({
  id: '/timeclock',
  path: '/timeclock',
  getParentRoute: () => PosRouteRoute,
} as any)
const PosRegisterRoute = PosRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PosRouteRoute,
} as any)
const PosRefundsRoute = PosRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => PosRouteRoute,
} as any)
const PosPosRoute = PosPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => PosRouteRoute,
} as any)
const DashboardShiftsRoute = DashboardShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSetupRoute = DashboardSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSalesRoute = DashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPayrollRoute = DashboardPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmployeesRoute = DashboardEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAppAdminIndexRoute = AdminAppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const LovableSmsSendRoute = LovableSmsSendRouteImport.update({
  id: '/lovable/sms/send',
  path: '/lovable/sms/send',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmployeesIdRoute = DashboardEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardEmployeesRoute,
} as any)
const AdminAppAdminSupportRoute = AdminAppAdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppAdminSubscriptionsRoute =
  AdminAppAdminSubscriptionsRouteImport.update({
    id: '/admin/subscriptions',
    path: '/admin/subscriptions',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)
const AdminAppAdminSettingsRoute = AdminAppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppAdminDevicesRoute = AdminAppAdminDevicesRouteImport.update({
  id: '/admin/devices',
  path: '/admin/devices',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppAdminAuditLogsRoute = AdminAppAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppAdminBusinessesIndexRoute =
  AdminAppAdminBusinessesIndexRouteImport.update({
    id: '/admin/businesses/',
    path: '/admin/businesses/',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPosVerifyManagerPinRoute =
  ApiPublicPosVerifyManagerPinRouteImport.update({
    id: '/api/public/pos/verify-manager-pin',
    path: '/api/public/pos/verify-manager-pin',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPosVerifyEmployeePinRoute =
  ApiPublicPosVerifyEmployeePinRouteImport.update({
    id: '/api/public/pos/verify-employee-pin',
    path: '/api/public/pos/verify-employee-pin',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAppAdminSupportTicketIdRoute =
  AdminAppAdminSupportTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AdminAppAdminSupportRoute,
  } as any)
const AdminAppAdminBusinessesStoreIdRoute =
  AdminAppAdminBusinessesStoreIdRouteImport.update({
    id: '/admin/businesses/$storeId',
    path: '/admin/businesses/$storeId',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/hardware': typeof HardwareRoute
  '/industries': typeof IndustriesRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/select-plan': typeof SelectPlanRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/customers': typeof DashboardCustomersRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/employees': typeof DashboardEmployeesRouteWithChildren
  '/help': typeof DashboardHelpRoute
  '/inventory': typeof DashboardInventoryRoute
  '/onboarding': typeof DashboardOnboardingRoute
  '/payroll': typeof DashboardPayrollRoute
  '/products': typeof DashboardProductsRoute
  '/reports': typeof DashboardReportsRoute
  '/sales': typeof DashboardSalesRoute
  '/settings': typeof DashboardSettingsRoute
  '/setup': typeof DashboardSetupRoute
  '/shifts': typeof DashboardShiftsRoute
  '/pos': typeof PosPosRoute
  '/refunds': typeof PosRefundsRoute
  '/register': typeof PosRegisterRoute
  '/timeclock': typeof PosTimeclockRoute
  '/admin/auth': typeof AdminAuthRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$id': typeof RIdRoute
  '/legal/': typeof LegalIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/audit-logs': typeof AdminAppAdminAuditLogsRoute
  '/admin/devices': typeof AdminAppAdminDevicesRoute
  '/admin/settings': typeof AdminAppAdminSettingsRoute
  '/admin/subscriptions': typeof AdminAppAdminSubscriptionsRoute
  '/admin/support': typeof AdminAppAdminSupportRouteWithChildren
  '/employees/$id': typeof DashboardEmployeesIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/sms/send': typeof LovableSmsSendRoute
  '/admin/': typeof AdminAppAdminIndexRoute
  '/admin/businesses/$storeId': typeof AdminAppAdminBusinessesStoreIdRoute
  '/admin/support/$ticketId': typeof AdminAppAdminSupportTicketIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/pos/verify-employee-pin': typeof ApiPublicPosVerifyEmployeePinRoute
  '/api/public/pos/verify-manager-pin': typeof ApiPublicPosVerifyManagerPinRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/businesses/': typeof AdminAppAdminBusinessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/hardware': typeof HardwareRoute
  '/industries': typeof IndustriesRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/select-plan': typeof SelectPlanRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/customers': typeof DashboardCustomersRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/employees': typeof DashboardEmployeesRouteWithChildren
  '/help': typeof DashboardHelpRoute
  '/inventory': typeof DashboardInventoryRoute
  '/onboarding': typeof DashboardOnboardingRoute
  '/payroll': typeof DashboardPayrollRoute
  '/products': typeof DashboardProductsRoute
  '/reports': typeof DashboardReportsRoute
  '/sales': typeof DashboardSalesRoute
  '/settings': typeof DashboardSettingsRoute
  '/setup': typeof DashboardSetupRoute
  '/shifts': typeof DashboardShiftsRoute
  '/pos': typeof PosPosRoute
  '/refunds': typeof PosRefundsRoute
  '/register': typeof PosRegisterRoute
  '/timeclock': typeof PosTimeclockRoute
  '/admin/auth': typeof AdminAuthRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$id': typeof RIdRoute
  '/legal': typeof LegalIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/audit-logs': typeof AdminAppAdminAuditLogsRoute
  '/admin/devices': typeof AdminAppAdminDevicesRoute
  '/admin/settings': typeof AdminAppAdminSettingsRoute
  '/admin/subscriptions': typeof AdminAppAdminSubscriptionsRoute
  '/admin/support': typeof AdminAppAdminSupportRouteWithChildren
  '/employees/$id': typeof DashboardEmployeesIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/sms/send': typeof LovableSmsSendRoute
  '/admin': typeof AdminAppAdminIndexRoute
  '/admin/businesses/$storeId': typeof AdminAppAdminBusinessesStoreIdRoute
  '/admin/support/$ticketId': typeof AdminAppAdminSupportTicketIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/pos/verify-employee-pin': typeof ApiPublicPosVerifyEmployeePinRoute
  '/api/public/pos/verify-manager-pin': typeof ApiPublicPosVerifyManagerPinRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/businesses': typeof AdminAppAdminBusinessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_adminApp': typeof AdminAppRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_pos': typeof PosRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/hardware': typeof HardwareRoute
  '/industries': typeof IndustriesRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/select-plan': typeof SelectPlanRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_dashboard/customers': typeof DashboardCustomersRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/employees': typeof DashboardEmployeesRouteWithChildren
  '/_dashboard/help': typeof DashboardHelpRoute
  '/_dashboard/inventory': typeof DashboardInventoryRoute
  '/_dashboard/onboarding': typeof DashboardOnboardingRoute
  '/_dashboard/payroll': typeof DashboardPayrollRoute
  '/_dashboard/products': typeof DashboardProductsRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/sales': typeof DashboardSalesRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/setup': typeof DashboardSetupRoute
  '/_dashboard/shifts': typeof DashboardShiftsRoute
  '/_pos/pos': typeof PosPosRoute
  '/_pos/refunds': typeof PosRefundsRoute
  '/_pos/register': typeof PosRegisterRoute
  '/_pos/timeclock': typeof PosTimeclockRoute
  '/admin/auth': typeof AdminAuthRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$id': typeof RIdRoute
  '/legal/': typeof LegalIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_adminApp/admin/audit-logs': typeof AdminAppAdminAuditLogsRoute
  '/_adminApp/admin/devices': typeof AdminAppAdminDevicesRoute
  '/_adminApp/admin/settings': typeof AdminAppAdminSettingsRoute
  '/_adminApp/admin/subscriptions': typeof AdminAppAdminSubscriptionsRoute
  '/_adminApp/admin/support': typeof AdminAppAdminSupportRouteWithChildren
  '/_dashboard/employees/$id': typeof DashboardEmployeesIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/sms/send': typeof LovableSmsSendRoute
  '/_adminApp/admin/': typeof AdminAppAdminIndexRoute
  '/_adminApp/admin/businesses/$storeId': typeof AdminAppAdminBusinessesStoreIdRoute
  '/_adminApp/admin/support/$ticketId': typeof AdminAppAdminSupportTicketIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/pos/verify-employee-pin': typeof ApiPublicPosVerifyEmployeePinRoute
  '/api/public/pos/verify-manager-pin': typeof ApiPublicPosVerifyManagerPinRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_adminApp/admin/businesses/': typeof AdminAppAdminBusinessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/features'
    | '/hardware'
    | '/industries'
    | '/integrations'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/robots.txt'
    | '/security'
    | '/select-plan'
    | '/signup'
    | '/sitemap.xml'
    | '/status'
    | '/support'
    | '/terms'
    | '/trust'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/help'
    | '/inventory'
    | '/onboarding'
    | '/payroll'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/setup'
    | '/shifts'
    | '/pos'
    | '/refunds'
    | '/register'
    | '/timeclock'
    | '/admin/auth'
    | '/email/unsubscribe'
    | '/legal/$slug'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/r/$id'
    | '/legal/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/audit-logs'
    | '/admin/devices'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/employees/$id'
    | '/lovable/email/suppression'
    | '/lovable/sms/send'
    | '/admin/'
    | '/admin/businesses/$storeId'
    | '/admin/support/$ticketId'
    | '/api/public/payments/webhook'
    | '/api/public/pos/verify-employee-pin'
    | '/api/public/pos/verify-manager-pin'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/businesses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/features'
    | '/hardware'
    | '/industries'
    | '/integrations'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/robots.txt'
    | '/security'
    | '/select-plan'
    | '/signup'
    | '/sitemap.xml'
    | '/status'
    | '/support'
    | '/terms'
    | '/trust'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/help'
    | '/inventory'
    | '/onboarding'
    | '/payroll'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/setup'
    | '/shifts'
    | '/pos'
    | '/refunds'
    | '/register'
    | '/timeclock'
    | '/admin/auth'
    | '/email/unsubscribe'
    | '/legal/$slug'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/r/$id'
    | '/legal'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/audit-logs'
    | '/admin/devices'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/employees/$id'
    | '/lovable/email/suppression'
    | '/lovable/sms/send'
    | '/admin'
    | '/admin/businesses/$storeId'
    | '/admin/support/$ticketId'
    | '/api/public/payments/webhook'
    | '/api/public/pos/verify-employee-pin'
    | '/api/public/pos/verify-manager-pin'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/businesses'
  id:
    | '__root__'
    | '/'
    | '/_adminApp'
    | '/_dashboard'
    | '/_pos'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/features'
    | '/hardware'
    | '/industries'
    | '/integrations'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/robots.txt'
    | '/security'
    | '/select-plan'
    | '/signup'
    | '/sitemap.xml'
    | '/status'
    | '/support'
    | '/terms'
    | '/trust'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_dashboard/customers'
    | '/_dashboard/dashboard'
    | '/_dashboard/employees'
    | '/_dashboard/help'
    | '/_dashboard/inventory'
    | '/_dashboard/onboarding'
    | '/_dashboard/payroll'
    | '/_dashboard/products'
    | '/_dashboard/reports'
    | '/_dashboard/sales'
    | '/_dashboard/settings'
    | '/_dashboard/setup'
    | '/_dashboard/shifts'
    | '/_pos/pos'
    | '/_pos/refunds'
    | '/_pos/register'
    | '/_pos/timeclock'
    | '/admin/auth'
    | '/email/unsubscribe'
    | '/legal/$slug'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/r/$id'
    | '/legal/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_adminApp/admin/audit-logs'
    | '/_adminApp/admin/devices'
    | '/_adminApp/admin/settings'
    | '/_adminApp/admin/subscriptions'
    | '/_adminApp/admin/support'
    | '/_dashboard/employees/$id'
    | '/lovable/email/suppression'
    | '/lovable/sms/send'
    | '/_adminApp/admin/'
    | '/_adminApp/admin/businesses/$storeId'
    | '/_adminApp/admin/support/$ticketId'
    | '/api/public/payments/webhook'
    | '/api/public/pos/verify-employee-pin'
    | '/api/public/pos/verify-manager-pin'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_adminApp/admin/businesses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAppRouteRoute: typeof AdminAppRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PosRouteRoute: typeof PosRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  HardwareRoute: typeof HardwareRoute
  IndustriesRoute: typeof IndustriesRoute
  IntegrationsRoute: typeof IntegrationsRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SecurityRoute: typeof SecurityRoute
  SelectPlanRoute: typeof SelectPlanRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminAuthRoute: typeof AdminAuthRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LegalSlugRoute: typeof LegalSlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  RIdRoute: typeof RIdRoute
  LegalIndexRoute: typeof LegalIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableSmsSendRoute: typeof LovableSmsSendRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicPosVerifyEmployeePinRoute: typeof ApiPublicPosVerifyEmployeePinRoute
  ApiPublicPosVerifyManagerPinRoute: typeof ApiPublicPosVerifyManagerPinRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-plan': {
      id: '/select-plan'
      path: '/select-plan'
      fullPath: '/select-plan'
      preLoaderRoute: typeof SelectPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pos': {
      id: '/_pos'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminApp': {
      id: '/_adminApp'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pos/timeclock': {
      id: '/_pos/timeclock'
      path: '/timeclock'
      fullPath: '/timeclock'
      preLoaderRoute: typeof PosTimeclockRouteImport
      parentRoute: typeof PosRouteRoute
    }
    '/_pos/register': {
      id: '/_pos/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PosRegisterRouteImport
      parentRoute: typeof PosRouteRoute
    }
    '/_pos/refunds': {
      id: '/_pos/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof PosRefundsRouteImport
      parentRoute: typeof PosRouteRoute
    }
    '/_pos/pos': {
      id: '/_pos/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosPosRouteImport
      parentRoute: typeof PosRouteRoute
    }
    '/_dashboard/shifts': {
      id: '/_dashboard/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof DashboardShiftsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/setup': {
      id: '/_dashboard/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/sales': {
      id: '/_dashboard/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof DashboardSalesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products': {
      id: '/_dashboard/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/payroll': {
      id: '/_dashboard/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof DashboardPayrollRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/onboarding': {
      id: '/_dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/inventory': {
      id: '/_dashboard/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/help': {
      id: '/_dashboard/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/employees': {
      id: '/_dashboard/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof DashboardEmployeesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/customers': {
      id: '/_dashboard/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminApp/admin/': {
      id: '/_adminApp/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAppAdminIndexRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/lovable/sms/send': {
      id: '/lovable/sms/send'
      path: '/lovable/sms/send'
      fullPath: '/lovable/sms/send'
      preLoaderRoute: typeof LovableSmsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/employees/$id': {
      id: '/_dashboard/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof DashboardEmployeesIdRouteImport
      parentRoute: typeof DashboardEmployeesRoute
    }
    '/_adminApp/admin/support': {
      id: '/_adminApp/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminAppAdminSupportRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/_adminApp/admin/subscriptions': {
      id: '/_adminApp/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminAppAdminSubscriptionsRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/_adminApp/admin/settings': {
      id: '/_adminApp/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAppAdminSettingsRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/_adminApp/admin/devices': {
      id: '/_adminApp/admin/devices'
      path: '/admin/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminAppAdminDevicesRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/_adminApp/admin/audit-logs': {
      id: '/_adminApp/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAppAdminAuditLogsRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminApp/admin/businesses/': {
      id: '/_adminApp/admin/businesses/'
      path: '/admin/businesses'
      fullPath: '/admin/businesses/'
      preLoaderRoute: typeof AdminAppAdminBusinessesIndexRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pos/verify-manager-pin': {
      id: '/api/public/pos/verify-manager-pin'
      path: '/api/public/pos/verify-manager-pin'
      fullPath: '/api/public/pos/verify-manager-pin'
      preLoaderRoute: typeof ApiPublicPosVerifyManagerPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pos/verify-employee-pin': {
      id: '/api/public/pos/verify-employee-pin'
      path: '/api/public/pos/verify-employee-pin'
      fullPath: '/api/public/pos/verify-employee-pin'
      preLoaderRoute: typeof ApiPublicPosVerifyEmployeePinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminApp/admin/support/$ticketId': {
      id: '/_adminApp/admin/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/support/$ticketId'
      preLoaderRoute: typeof AdminAppAdminSupportTicketIdRouteImport
      parentRoute: typeof AdminAppAdminSupportRoute
    }
    '/_adminApp/admin/businesses/$storeId': {
      id: '/_adminApp/admin/businesses/$storeId'
      path: '/admin/businesses/$storeId'
      fullPath: '/admin/businesses/$storeId'
      preLoaderRoute: typeof AdminAppAdminBusinessesStoreIdRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
  }
}

interface AdminAppAdminSupportRouteChildren {
  AdminAppAdminSupportTicketIdRoute: typeof AdminAppAdminSupportTicketIdRoute
}

const AdminAppAdminSupportRouteChildren: AdminAppAdminSupportRouteChildren = {
  AdminAppAdminSupportTicketIdRoute: AdminAppAdminSupportTicketIdRoute,
}

const AdminAppAdminSupportRouteWithChildren =
  AdminAppAdminSupportRoute._addFileChildren(AdminAppAdminSupportRouteChildren)

interface AdminAppRouteRouteChildren {
  AdminAppAdminAuditLogsRoute: typeof AdminAppAdminAuditLogsRoute
  AdminAppAdminDevicesRoute: typeof AdminAppAdminDevicesRoute
  AdminAppAdminSettingsRoute: typeof AdminAppAdminSettingsRoute
  AdminAppAdminSubscriptionsRoute: typeof AdminAppAdminSubscriptionsRoute
  AdminAppAdminSupportRoute: typeof AdminAppAdminSupportRouteWithChildren
  AdminAppAdminIndexRoute: typeof AdminAppAdminIndexRoute
  AdminAppAdminBusinessesStoreIdRoute: typeof AdminAppAdminBusinessesStoreIdRoute
  AdminAppAdminBusinessesIndexRoute: typeof AdminAppAdminBusinessesIndexRoute
}

const AdminAppRouteRouteChildren: AdminAppRouteRouteChildren = {
  AdminAppAdminAuditLogsRoute: AdminAppAdminAuditLogsRoute,
  AdminAppAdminDevicesRoute: AdminAppAdminDevicesRoute,
  AdminAppAdminSettingsRoute: AdminAppAdminSettingsRoute,
  AdminAppAdminSubscriptionsRoute: AdminAppAdminSubscriptionsRoute,
  AdminAppAdminSupportRoute: AdminAppAdminSupportRouteWithChildren,
  AdminAppAdminIndexRoute: AdminAppAdminIndexRoute,
  AdminAppAdminBusinessesStoreIdRoute: AdminAppAdminBusinessesStoreIdRoute,
  AdminAppAdminBusinessesIndexRoute: AdminAppAdminBusinessesIndexRoute,
}

const AdminAppRouteRouteWithChildren = AdminAppRouteRoute._addFileChildren(
  AdminAppRouteRouteChildren,
)

interface DashboardEmployeesRouteChildren {
  DashboardEmployeesIdRoute: typeof DashboardEmployeesIdRoute
}

const DashboardEmployeesRouteChildren: DashboardEmployeesRouteChildren = {
  DashboardEmployeesIdRoute: DashboardEmployeesIdRoute,
}

const DashboardEmployeesRouteWithChildren =
  DashboardEmployeesRoute._addFileChildren(DashboardEmployeesRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardEmployeesRoute: typeof DashboardEmployeesRouteWithChildren
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardPayrollRoute: typeof DashboardPayrollRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSalesRoute: typeof DashboardSalesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSetupRoute: typeof DashboardSetupRoute
  DashboardShiftsRoute: typeof DashboardShiftsRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardEmployeesRoute: DashboardEmployeesRouteWithChildren,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardPayrollRoute: DashboardPayrollRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSalesRoute: DashboardSalesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSetupRoute: DashboardSetupRoute,
  DashboardShiftsRoute: DashboardShiftsRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface PosRouteRouteChildren {
  PosPosRoute: typeof PosPosRoute
  PosRefundsRoute: typeof PosRefundsRoute
  PosRegisterRoute: typeof PosRegisterRoute
  PosTimeclockRoute: typeof PosTimeclockRoute
}

const PosRouteRouteChildren: PosRouteRouteChildren = {
  PosPosRoute: PosPosRoute,
  PosRefundsRoute: PosRefundsRoute,
  PosRegisterRoute: PosRegisterRoute,
  PosTimeclockRoute: PosTimeclockRoute,
}

const PosRouteRouteWithChildren = PosRouteRoute._addFileChildren(
  PosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAppRouteRoute: AdminAppRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PosRouteRoute: PosRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  HardwareRoute: HardwareRoute,
  IndustriesRoute: IndustriesRoute,
  IntegrationsRoute: IntegrationsRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SecurityRoute: SecurityRoute,
  SelectPlanRoute: SelectPlanRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminAuthRoute: AdminAuthRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LegalSlugRoute: LegalSlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  RIdRoute: RIdRoute,
  LegalIndexRoute: LegalIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableSmsSendRoute: LovableSmsSendRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicPosVerifyEmployeePinRoute: ApiPublicPosVerifyEmployeePinRoute,
  ApiPublicPosVerifyManagerPinRoute: ApiPublicPosVerifyManagerPinRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
